### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by junekyoopark** [sniklaus/pytorch-sepconv#27]
Install.bash ran with error 
```
In file included from /home/john/anaconda3/lib/python3.7/site-packages/torch/lib/include/THC/THCGeneral.h:5:0,
                 from /home/john/anaconda3/lib/python3.7/site-packages/torch/lib/include/THC/THC.h:4,
                 from src/SeparableConvolution_kernel.cu:1:
/home/john/anaconda3/lib/python3.7/site-packages/torch/lib/include/TH/THAllocator.h:6:10: fatal error: ATen/Allocator.h: No such file or directory
 #include <ATen/Allocator.h>
          ^~~~~~~~~~~~~~~~~~

```
but it still proceeded with downloads. Then, when run run.py, it gives a Segmentation Fault.

CUDA version 10, Pytorch 0.4.1. Ubuntu 18.04

EDIT: works fine on Ubuntu 16.04, Pytorch 0.4.0, CUDA 8.0. Initially faced some errors in install.bash, but changed `python install.py` to `python3 install.py` (inside install.bash) and works fine. Also had to add CUDA to PATH for PyTorch to recognize it properly. Will see if it works again on recent versions.

**Comment by sniklaus** [comment]
Please note that this repository does not contain a `install.bash` anymore. Are you using the most recent version?
